// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqJlEKMY6ZbLh70g8OcQoUOfC87KKDDY',
    appId: '1:966577050227:web:2dd81d73a2faee43c21006',
    messagingSenderId: '966577050227',
    projectId: 'sewaconnect-3791d',
    authDomain: 'sewaconnect-3791d.firebaseapp.com',
    storageBucket: 'sewaconnect-3791d.firebasestorage.app',
    measurementId: 'G-KH76VZW0R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtroeuyADDNG1QXEkTDkmzbxQnTySr2Lc',
    appId: '1:966577050227:android:07e4f37704b8df4ec21006',
    messagingSenderId: '966577050227',
    projectId: 'sewaconnect-3791d',
    storageBucket: 'sewaconnect-3791d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6arie_9LzFtw_9ArXjTQtaDqByiNgjI',
    appId: '1:966577050227:ios:75eeaee2769fbff1c21006',
    messagingSenderId: '966577050227',
    projectId: 'sewaconnect-3791d',
    storageBucket: 'sewaconnect-3791d.firebasestorage.app',
    iosBundleId: 'com.example.sewaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp6arie_9LzFtw_9ArXjTQtaDqByiNgjI',
    appId: '1:966577050227:ios:75eeaee2769fbff1c21006',
    messagingSenderId: '966577050227',
    projectId: 'sewaconnect-3791d',
    storageBucket: 'sewaconnect-3791d.firebasestorage.app',
    iosBundleId: 'com.example.sewaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMqJlEKMY6ZbLh70g8OcQoUOfC87KKDDY',
    appId: '1:966577050227:web:f8c2bff68a16e5d2c21006',
    messagingSenderId: '966577050227',
    projectId: 'sewaconnect-3791d',
    authDomain: 'sewaconnect-3791d.firebaseapp.com',
    storageBucket: 'sewaconnect-3791d.firebasestorage.app',
    measurementId: 'G-TRCRT1VVP2',
  );
}
